### ISSUE TITLE
Allow specifying the error message for disallowed mimeTypes

### ISSUE THREAD

**Issue by darinda** [netgen/NetgenEnhancedBinaryFileBundle#12]
Symfony allows for specifying the error message that will be shown when the user selects a file of a mime type that is disallowed (https://symfony.com/doc/current/reference/constraints/File.html#mimetypesmessage)

It would be nice to be able to define that error message on content type level in the admin interface.

**Comment by darinda** [comment]
Implemented in https://github.com/darinda/NetgenEnhancedBinaryFileBundle/commit/826f21b3ff27ea3bae214926024b8d7ee2447a13
But PR #11 should be merged first.

**Comment by MarioBlazek** [comment]
@darinda, please create PR based on the code from your fork. Just one notice, maybe a better solution would be to use `mimeTypeMessage` from translation file rather than saving/reading it from the database.

**Comment by darinda** [comment]
@MarioBlazek PR has been created. I moved the mimeTypeMessage to the database because it can be translated there. ContentTypes can be translated, so i think this is the correct place to put them.

That way the mimeTypeMessage can be specified like "Please upload only PDF documents!" instead of having the standard symfony message stating something about the mime types which a normal end user won't be able to understand.

**Comment by emodric** [comment]
Hm, that might make sense. What happens if we leave it to an empty value?

**Comment by darinda** [comment]
> What happens if we leave it to an empty value?

Then [symfony's default error message](https://symfony.com/doc/current/reference/constraints/File.html)  will be displayed, as it was before this pull request.

So `The mime type of the file is invalid ({{ type }}). Allowed mime types are {{ types }}.`

**Comment by darinda** [comment]
@emodric bump ;)

**Comment by emodric** [comment]
I've left a couple of comments on #13.

Otherwise, if everything works, I'm +1 for merging.

@MarioBlazek What do you think?
