### ISSUE TITLE
There can be filename collisions for files uploaded as part of infocollection

### ISSUE THREAD

**Issue by darinda** [netgen/NetgenEnhancedBinaryFileBundle#9]
Since files that are uploaded as part of a information collection (using https://github.com/netgen/NetgenInformationCollectionBundle) are placed on a fixed location on the disk (`<storage_dir>/original/collected/<filename>`) filename collisions are likely to happen, resulting in files getting overwritten on the disk.

Additionally this is a security/privacy risk because filenames could relatively easily be guessed allowing access to those files via above mentioned url scheme.

The filenames should be replaced by hash values on upload, storing these hash values in the collection attributes. Additionally, a controller to download the files (using the original filename) should be implemented, allowing for permission checks, too.

**Comment by darinda** [comment]
I suggest the following changes (which i'm happy to provide as a pull request)

1) Rename the uploaded file to a generated value (`uniqid`) in [EnhancedBinaryFileHandler](https://github.com/netgen/NetgenEnhancedBinaryFileBundle/blob/master/bundle/FieldHandler/EnhancedBinaryFileHandler.php#L105)

2) Provide a `DownloadController` that's based on [the download controller from ezbinaryfile](https://github.com/ezsystems/ezpublish-kernel/blob/master/eZ/Publish/Core/MVC/Symfony/Controller/Content/DownloadController.php#L44) taking the information collection id, infocollection attribute id and filename as arguments

That controller should also respect the `infocollector/read` permission which so far only exists in legacy but actually should be implemented in [NetgenInformationCollectionBundle](https://github.com/netgen/NetgenInformationCollectionBundle)

What are your thoughts on this?

**Comment by emodric** [comment]
Sounds good :)

Thanks for the issue and future PR :) :+1:

**Comment by darinda** [comment]
could this PR be merged?
